on:
  workflow_dispatch:

name: Fetch Epiverse-CONNECT R-universe documentation

jobs:
  fetch-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages:
            local::.

      - run: |
          epiverse.scraper::get_universe_docs()
          tar("docs.tar.gz", "docs", compression = "gzip")
        shell: Rscript {0}

      - name: Tag new release and attach new data
        run: |
          gh release create v$(date +'%Y-%m-%d')
          gh release upload v$(date +'%Y-%m-%d') docs.tar.gz

      - name: Remove data from previous release
        run: |
          OLD_RELEASE = $(gh release list --json tagName --jq '.[1].tagName')
          gh release delete-asset $OLD_RELEASE docs.tar.gz -y